let dados = {
    "DC": [
        {
            "Nome": "Super Homem",
            "Nome de batismo": "Kal-El",
            "Criadores": "Jerry Siegel e Joe Shuster",
            "Ano de criação": 1938,
            "Origem": "Nascido no planeta Krypton, foi enviado à Terra por seus pais biológicos antes da destruição de seu planeta. Criado por uma família no Kansas, adotou a identidade de Clark Kent.",
            "Nome dos pais": "Jor-El e Lara Lor-Van (biológicos), Jonathan e Martha Kent (adotivos)",
            "Personalidade": "Defensor da justiça, moralmente íntegro e conhecido por sua compaixão e senso de dever.",
            "Fraquezas": "Kryptonita, magia, falta de radiação solar amarela.",
            "Afiliações": "Liga da Justiça.",
            "Ficha técnica": "Alienígena de Krypton com super força, voo, visão de calor e outros poderes.",
            "Principais inimigos": "Lex Luthor, General Zod, Brainiac."
        },
        {
            "Nome": "Mulher Maravilha",
            "Nome de batismo": "Diana",
            "Criadores": "William Moulton Marston",
            "Ano de criação": 1941,
            "Origem": "Princesa amazona de Themyscira, uma ilha isolada habitada por mulheres guerreiras. Criada por sua mãe, Rainha Hipólita, e abençoada pelos deuses.",
            "Nome dos pais": "Rainha Hipólita (mãe)",
            "Personalidade": "Forte, corajosa, empática e com um senso inabalável de justiça.",
            "Fraquezas": "Ligação com a verdade (laço da verdade a impede de mentir), armas mágicas.",
            "Afiliações": "Liga da Justiça.",
            "Ficha técnica": "Super força, agilidade, voo, longevidade, mestre em combate e armas.",
            "Principais inimigos": "Ares, Cheetah, Circe."
        },
        {
            "Nome": "Supergirl",
            "Nome de batismo": "Kara Zor-El",
            "Criadores": "Otto Binder e Al Plastino",
            "Ano de criação": 1959,
            "Origem": "Prima do Superman, também é uma sobrevivente de Krypton, enviada à Terra antes da destruição de seu planeta.",
            "Nome dos pais": "Zor-El e Alura In-Ze",
            "Personalidade": "Determinada, corajosa e às vezes impulsiva, com um desejo forte de provar seu valor.",
            "Fraquezas": "Kryptonita, magia, falta de radiação solar amarela.",
            "Afiliações": "Liga da Justiça, Jovens Titãs.",
            "Ficha técnica": "Super força, voo, visão de calor e raios-X, audição super aguçada.",
            "Principais inimigos": "Brainiac, Cyborg Superman, Reactron."
        },
        {
            "Nome": "Flash",
            "Nome de batismo": "Barry Allen",
            "Criadores": "Gardner Fox e Harry Lampert",
            "Ano de criação": 1940,
            "Origem": "Barry Allen era um cientista forense que ganhou seus poderes de supervelocidade após ser atingido por um raio e exposto a produtos químicos.",
            "Nome dos pais": "Henry Allen e Nora Allen",
            "Personalidade": "Engraçado, otimista e determinado a usar sua velocidade para salvar o mundo.",
            "Fraquezas": "Necessidade de consumir grandes quantidades de energia, Força de Aceleração instável.",
            "Afiliações": "Liga da Justiça.",
            "Ficha técnica": "Supervelocidade, capacidade de viajar no tempo, acessar a Força de Aceleração.",
            "Principais inimigos": "Flash Reverso, Capitão Frio, Zoom."
        },
        {
            "Nome": "Estelar",
            "Nome de batismo": "Koriand'r",
            "Criadores": "Marv Wolfman e George Pérez",
            "Ano de criação": 1980,
            "Origem": "Princesa do planeta Tamaran, foi exilada após um golpe de estado e chegou à Terra, onde se uniu aos Jovens Titãs.",
            "Nome dos pais": "Rei Myand'r e Rainha Luand'r",
            "Personalidade": "Alegre, curiosa e calorosa, mas feroz em batalha quando necessário.",
            "Fraquezas": "Emoções intensas podem prejudicar sua capacidade de usar seus poderes.",
            "Afiliações": "Jovens Titãs.",
            "Ficha técnica": "Voo, super força, disparos de energia estelar, habilidades de combate.",
            "Principais inimigos": "Irmã Estrela Negra, Komand'r."
        },
        {
            "Nome": "Ravena",
            "Nome de batismo": "Rachel Roth",
            "Criadores": "Marv Wolfman e George Pérez",
            "Ano de criação": 1980,
            "Origem": "Filha do demônio Trigon e de uma humana, cresceu em um templo espiritual tentando controlar seus poderes sombrios.",
            "Nome dos pais": "Trigon (pai), Arella (mãe)",
            "Personalidade": "Reservada, introvertida, com um constante esforço para controlar suas emoções.",
            "Fraquezas": "Se perder o controle emocional, pode liberar o lado sombrio de seus poderes.",
            "Afiliações": "Jovens Titãs.",
            "Ficha técnica": "Magia negra, telepatia, teletransporte, projeção astral.",
            "Principais inimigos": "Trigon, Irmãos do Sangue."
        },
        {
            "Nome": "Asa Noturna",
            "Nome de batismo": "Dick Grayson",
            "Criadores": "Bob Kane e Bill Finger",
            "Ano de criação": "1940 (como Robin), 1984 (como Asa Noturna)",
            "Origem": "Dick Grayson, o primeiro Robin, foi adotado por Bruce Wayne após a morte de seus pais. Mais tarde, ele assumiu sua própria identidade como Asa Noturna.",
            "Nome dos pais": "John e Mary Grayson",
            "Personalidade": "Independente, carismático e um líder nato, com forte senso de justiça.",
            "Fraquezas": "Humano, vulnerável a ferimentos físicos graves.",
            "Afiliações": "Jovens Titãs, Liga da Justiça.",
            "Ficha técnica": "Habilidades acrobáticas, mestre em combate, expert em investigação.",
            "Principais inimigos": "Exterminador, Blockbuster, Coruja."
        },
        {
            "Nome": "Ajax",
            "Nome de batismo": "J'onn J'onzz",
            "Criadores": "Joseph Samachson e Joe Certa",
            "Ano de criação": 1955,
            "Origem": "Último sobrevivente do planeta Marte, J'onn J'onzz foi transportado acidentalmente para a Terra, onde se tornou um defensor da humanidade.",
            "Nome dos pais": "M'yrnn e Sha'sheen J'onzz",
            "Personalidade": "Calmo, contemplativo, com grande empatia e senso de justiça.",
            "Fraquezas": "Fogo.",
            "Afiliações": "Liga da Justiça.",
            "Ficha técnica": "Telepatia, intangibilidade, metamorfose, super força, voo.",
            "Principais inimigos": "Malefic, Ma'alefa'ak, White Martians."
        },
        {
            "Nome": "Batman",
            "Nome de batismo": "Bruce Wayne",
            "Criadores": "Bob Kane e Bill Finger",
            "Ano de criação": 1939,
            "Origem": "Bruce Wayne testemunhou o assassinato de seus pais quando criança e jurou combater o crime em Gotham City como o vigilante conhecido como Batman.",
            "Nome dos pais": "Thomas e Martha Wayne",
            "Personalidade": "Sombrio, determinado, com um forte código moral e um intelecto genial.",
            "Fraquezas": "Humano, vulnerável a ferimentos físicos.",
            "Afiliações": "Liga da Justiça, Bat-família.",
            "Ficha técnica": "Intelecto genial, mestre em artes marciais, uso de gadgets avançados, detetive excepcional.",
            "Principais inimigos": "Coringa, Charada, Bane."
        },
        {
            "Nome": "Cyborg",
            "Nome de batismo": "Victor Stone",
            "Criadores": "Marv Wolfman e George Pérez",
            "Ano de criação": 1980,
            "Origem": "Victor Stone foi gravemente ferido em um acidente, e seu pai cientista o salvou ao reconstruí-lo com tecnologia cibernética alienígena.",
            "Nome dos pais": "Silas Stone (pai), Elinore Stone (mãe)",
            "Personalidade": "Inteligente, confiável, mas muitas vezes lutando com sua própria identidade entre humano e máquina.",
            "Fraquezas": "Interferência tecnológica pode afetar seus sistemas, e falhas no sistema cibernético podem causar paralisia temporária.",
            "Afiliações": "Liga da Justiça, Jovens Titãs.",
            "Ficha técnica": "Super força, invulnerabilidade, habilidades de hackeamento, várias armas tecnológicas integradas ao seu corpo.",
            "Principais inimigos": "Grid, Irmão Sangue, Darkseid."
        },
],

    "Marvel": [
        {
            "Nome": "Homem-Aranha",
            "Nome de batismo": "Peter Parker",
            "Criadores": "Stan Lee e Steve Ditko",
            "Ano de criação": 1962,
            "Origem": "Peter Parker era um estudante do ensino médio que foi picado por uma aranha radioativa, ganhando habilidades sobre-humanas. Após a morte de seu tio Ben, Peter adota a identidade de Homem-Aranha e se compromete a lutar contra o crime.",
            "Nome dos pais": "Richard Parker (pai), Mary Parker (mãe)",
            "Personalidade": "Inteligente, espirituoso e com um forte senso de responsabilidade, muitas vezes lida com dilemas pessoais enquanto luta para proteger Nova York.",
            "Fraquezas": "Falta de experiência e auto-dúvida, vulnerabilidade emocional.",
            "Afiliações": "Vingadores, Quarteto Fantástico (ocasionalmente).",
            "Ficha técnica": "Super força, agilidade, reflexos rápidos, sentido de aranha, habilidade de escalar paredes e lançar teias.",
            "Principais inimigos": "Duende Verde, Doutor Octopus, Venom, Lagarto."
        },
        {
            "Nome": "Demolidor",
            "Nome de batismo": "Matthew 'Matt' Murdock",
            "Criadores": "Stan Lee e Bill Everett",
            "Ano de criação": 1964,
            "Origem": "Matt Murdock ficou cego quando criança após um acidente com produtos químicos, mas os outros sentidos de seu corpo foram aprimorados a níveis sobre-humanos. Ele se tornou advogado durante o dia e o vigilante Demolidor à noite, para proteger Hell's Kitchen.",
            "Nome dos pais": "Jack Murdock (pai), Maggie Murdock (mãe)",
            "Personalidade": "Resiliente, moralmente forte e com uma busca incansável por justiça, tanto como advogado quanto como herói.",
            "Fraquezas": "Sua cegueira o limita em alguns aspectos, e seu forte senso de justiça o coloca em perigo.",
            "Afiliações": "Defensores.",
            "Ficha técnica": "Sentidos aumentados, habilidades acrobáticas, mestre em artes marciais, detecção de sons e movimentos.",
            "Principais inimigos": "Wilson Fisk (Rei do Crime), Mercenário, Mão."
        },
        {
            "Nome": "Feiticeira Escarlate",
            "Nome de batismo": "Wanda Maximoff",
            "Criadores": "Stan Lee e Jack Kirby",
            "Ano de criação": 1964,
            "Origem": "Wanda Maximoff e seu irmão, Pietro, foram originalmente apresentados como filhos de Magneto. Ela possui poderes de manipulação da realidade e da magia, adquiridos inicialmente por experimentos genéticos.",
            "Nome dos pais": "Magda Eisenhardt (mãe), Magneto (pai adotivo em algumas versões)",
            "Personalidade": "Intensa e emocionalmente complexa, às vezes lutando com o controle de seus vastos poderes.",
            "Fraquezas": "Instabilidade emocional e mental, que pode amplificar seus poderes de forma destrutiva.",
            "Afiliações": "Vingadores, Irmandade de Mutantes (anteriormente).",
            "Ficha técnica": "Manipulação da realidade, poderes mágicos, controle de probabilidades e energia.",
            "Principais inimigos": "Ultron, Agatha Harkness, Dormammu."
        },
        {
            "Nome": "Capitão América",
            "Nome de batismo": "Steve Rogers",
            "Criadores": "Joe Simon e Jack Kirby",
            "Ano de criação": 1941,
            "Origem": "Steve Rogers era um jovem fraco e determinado que se voluntariou para o experimento do 'Soro do Super-Soldado', que lhe deu força e agilidade sobre-humanas. Durante a Segunda Guerra Mundial, ele se tornou o Capitão América e símbolo de esperança.",
            "Nome dos pais": "Sarah Rogers (mãe), Joseph Rogers (pai)",
            "Personalidade": "Leal, corajoso e com um senso inabalável de moralidade e justiça.",
            "Fraquezas": "Não possui poderes sobre-humanos além do soro. Pode ser emocionalmente vulnerável ao sacrifício e à perda.",
            "Afiliações": "Vingadores.",
            "Ficha técnica": "Força, agilidade e reflexos aprimorados, mestre em combate corpo a corpo, uso de escudo indestrutível.",
            "Principais inimigos": "Caveira Vermelha, Barão Zemo, Soldado Invernal."
        },
        {
            "Nome": "Homem de Ferro",
            "Nome de batismo": "Tony Stark",
            "Criadores": "Stan Lee, Larry Lieber, Don Heck e Jack Kirby",
            "Ano de criação": 1963,
            "Origem": "Tony Stark, um gênio, bilionário e inventor, construiu a armadura do Homem de Ferro após ser sequestrado e ferido no Afeganistão. Usando sua tecnologia para escapar, ele decide se tornar um herói e lutar contra ameaças globais.",
            "Nome dos pais": "Howard Stark (pai), Maria Stark (mãe)",
            "Personalidade": "Sarcástico, confiante, mas muitas vezes lutando com questões pessoais e responsabilidade moral.",
            "Fraquezas": "Dependência tecnológica e seus próprios demônios internos, como o alcoolismo.",
            "Afiliações": "Vingadores.",
            "Ficha técnica": "Inteligência de gênio, habilidades tecnológicas avançadas, armaduras com voo, força e poder de fogo.",
            "Principais inimigos": "Mandarim, Obadiah Stane, Ultron."
        },
        {
            "Nome": "Hulk",
            "Nome de batismo": "Bruce Banner",
            "Criadores": "Stan Lee e Jack Kirby",
            "Ano de criação": 1962,
            "Origem": "Bruce Banner foi exposto a uma dose maciça de radiação gama durante um experimento, o que o transformou no Hulk, uma criatura com força incomensurável que aparece quando Bruce fica com raiva.",
            "Nome dos pais": "Brian Banner (pai), Rebecca Banner (mãe)",
            "Personalidade": "Bruce é calmo e reservado, enquanto o Hulk é impulsivo, destrutivo, mas muitas vezes também um protetor dos inocentes.",
            "Fraquezas": "Perda de controle sobre sua forma Hulk, o que pode causar destruição indesejada.",
            "Afiliações": "Vingadores.",
            "Ficha técnica": "Força física incomparável, resistência, fator de cura acelerado, invulnerabilidade.",
            "Principais inimigos": "Abominável, Líder, General Ross."
        },
        {
            "Nome": "Thor",
            "Nome de batismo": "Thor Odinson",
            "Criadores": "Stan Lee, Larry Lieber e Jack Kirby",
            "Ano de criação": 1962,
            "Origem": "Filho de Odin, Thor é o deus do trovão e herdeiro do trono de Asgard. Ele foi enviado à Terra para aprender a humildade e se tornou um defensor do planeta.",
            "Nome dos pais": "Odin (pai), Frigga (mãe)",
            "Personalidade": "Nobre, corajoso, mas às vezes arrogante e impetuoso, com grande amor por sua terra natal e por seus aliados.",
            "Fraquezas": "Sua arrogância pode ser sua maior fraqueza. Além disso, sem Mjolnir, seu poder é limitado.",
            "Afiliações": "Vingadores.",
            "Ficha técnica": "Super força, controle do trovão e relâmpagos, voo com Mjolnir, imortalidade.",
            "Principais inimigos": "Loki, Hela, Surtur."
        },
        {
            "Nome": "Wolverine",
            "Nome de batismo": "James Howlett (Logan)",
            "Criadores": "Roy Thomas, Len Wein e John Romita Sr.",
            "Ano de criação": 1974,
            "Origem": "Logan, ou James Howlett, nasceu no século 19 e teve uma vida marcada por perda e dor. Seus poderes mutantes incluem fator de cura acelerado e garras ósseas, que foram revestidas com adamantium em um experimento militar.",
            "Nome dos pais": "John Howlett (pai), Elizabeth Howlett (mãe)",
            "Personalidade": "Durão, rebelde e solitário, mas com um forte código de honra e lealdade a seus amigos.",
            "Fraquezas": "Sua natureza solitária o afasta dos outros e ele pode ser controlado mentalmente.",
            "Afiliações": "X-Men, Vingadores.",
            "Ficha técnica": "Fator de cura, sentidos aguçados, garras de adamantium, longevidade.",
            "Principais inimigos": "Dentes de Sabre, Magneto, Arma X."
        },
        {
            "Nome": "Viúva Negra",
            "Nome de batismo": "Natasha Romanoff",
            "Criadores": "Stan Lee, Don Rico e Don Heck",
            "Ano de criação": 1964,
            "Origem": "Natasha Romanoff foi treinada como espiã desde jovem pela KGB, mas eventualmente desertou para os Estados Unidos, onde se juntou à S.H.I.E.L.D. e aos Vingadores.",
            "Nome dos pais": "Desconhecidos (órfã)",
            "Personalidade": "Fria e calculista em missões, mas leal e protetora de seus aliados, com um forte senso de redenção.",
            "Fraquezas": "Apesar de suas habilidades impressionantes, ela é apenas humana e pode ser ferida ou morta. Também lida com a culpa de seu passado sombrio.",
            "Afiliações": "Vingadores.",
            "Ficha técnica": "Mestre em combate corpo a corpo, espionagem, uso de armas e tecnologia avançada.",
            "Principais inimigos": "Treinador (Taskmaster), General Dreykov, Viúva de Ferro (Yelena Belova)."
        }
]};